version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "3001:27017"
    volumes:
      - ./mongo/dump:/dump
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh
